language: node_js
node_js:
  - "0.8"
before_install:
  - npm install -g npm@1.4.23
before_script:
  - psql -c 'create database forum;' -U postgres
  - psql -c 'create database forum_test;' -U postgres
