language: node_js
node_js:
  - "0.8"
before_script:
  - psql -c 'create database forum;' -U postgres
  - psql -d forum -c 'create table post (
        id serial primary key,
        body text,
        user_id integer,
        created_at timestamp,
        updated_at timestamp
    );' -U postgres
